<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SaintSeiyaNesReborn.OriginalSpec/SaintSeiyaNesReborn.OriginalSpec.csproj" />
    <ProjectReference Include="../SaintSeiyaNesReborn.Reborn.Core/SaintSeiyaNesReborn.Reborn.Core.csproj" />
  </ItemGroup>
</Project>
