#!/usr/bin/env python3
"""Clean-room decoder for Saint Seiya: Ougon Densetsu Kanketsu Hen passwords.

This implements behavior reverse engineered from the canonical Japanese ROM.
Input is the 31 numeric grid indices (0-based) used by the game's password
screen, not Japanese text glyphs.

The current tool focuses on decoding because it is already sufficient for
compatibility/import tests. The original encoder has an asymmetry in its
last partial bit group, so an encoder should be added only with explicit
compatibility tests against passwords generated by the original game.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import reduce
from operator import xor
from typing import Iterable, Sequence


class PasswordError(ValueError):
    pass


@dataclass(frozen=True)
class SaintRecord:
    """One persistent Saint record reconstructed from the password payload.

    Original five-byte order is:
    [Life low-two BCD digits, Life hundreds, Cosmo low-two BCD digits,
     Cosmo hundreds, packed resource-cap byte].

    The cap byte stores exclusive hundreds boundaries:
    high nibble = Life boundary, low nibble = Cosmo boundary.
    For the normal values used by the game, maximum = boundary*100 - 1.
    """

    life_low_bcd: int
    life_hundreds: int
    cosmo_low_bcd: int
    cosmo_hundreds: int
    cap_byte: int

    @property
    def life(self) -> int:
        return self.life_hundreds * 100 + bcd_byte_to_int(self.life_low_bcd)

    @property
    def cosmo(self) -> int:
        return self.cosmo_hundreds * 100 + bcd_byte_to_int(self.cosmo_low_bcd)

    @property
    def life_cap_boundary(self) -> int:
        return (self.cap_byte >> 4) & 0x0F

    @property
    def cosmo_cap_boundary(self) -> int:
        return self.cap_byte & 0x0F

    @staticmethod
    def _boundary_to_max(boundary: int) -> int:
        # Boundary zero is not observed for normal initialized Saints; expose
        # it conservatively as zero rather than inventing a negative maximum.
        return max(0, boundary * 100 - 1)

    @property
    def life_max(self) -> int:
        return self._boundary_to_max(self.life_cap_boundary)

    @property
    def cosmo_max(self) -> int:
        return self._boundary_to_max(self.cosmo_cap_boundary)


@dataclass(frozen=True)
class DecodedPassword:
    symbols: tuple[int, ...]
    payload: tuple[int, ...]
    saints: tuple[SaintRecord, ...]
    seventh_sense: int
    raw_05ac: int
    progress_0100: int
    raw_0101: int
    raw_0587: int
    raw_0588: int
    raw_0589: int
    raw_058a: int


def bcd_byte_to_int(value: int) -> int:
    hi = (value >> 4) & 0x0F
    lo = value & 0x0F
    if hi > 9 or lo > 9:
        raise PasswordError(f"invalid packed-decimal byte: 0x{value:02X}")
    return hi * 10 + lo


def _ror8(value: int, carry_in: int) -> tuple[int, int]:
    carry_out = value & 1
    return ((value >> 1) | ((carry_in & 1) << 7)) & 0xFF, carry_out


def _unpack_six_bit_stream(symbols: Sequence[int]) -> list[int]:
    """Mirror ROM helper $B04C and reconstruct its 24-byte work payload."""

    work = [0] * 0x80
    work[:31] = symbols

    x = 7
    y = 0x17
    while x >= 0:
        for _ in range(3):
            a = 0

            carry = work[x] & 1
            work[x] >>= 1
            a, _ = _ror8(a, carry)

            carry = work[x] & 1
            work[x] >>= 1
            a, _ = _ror8(a, carry)

            # $06B4 is eight bytes after base $06AC.
            a |= work[8 + y]
            work[0x20 + y] = a & 0xFF  # $06CC relative to $06AC
            y -= 1
        x -= 1

    return work[0x20 : 0x20 + 24]


def decode_symbols(values: Iterable[int]) -> DecodedPassword:
    symbols = [int(v) for v in values]
    if len(symbols) != 31:
        raise PasswordError(f"password must contain 31 symbols, got {len(symbols)}")
    if any(v < 0 or v > 0xFF for v in symbols):
        raise PasswordError("symbols must fit in one byte")

    # ROM validation: XOR of all 31 entered symbols must be zero.
    if reduce(xor, symbols, 0) != 0:
        raise PasswordError("checksum mismatch")

    # Undo the ROM's 10-symbol XOR-$3F obfuscation window.
    work = symbols.copy()
    start = work[30] & 0x0F
    for i in range(10):
        work[start + i] ^= 0x3F

    expanded = _unpack_six_bit_stream(work)
    payload = expanded[:22]

    saints: list[SaintRecord] = []
    for i in range(4):
        life_low, cosmo_low, cap_byte, packed_high = payload[i * 4 : i * 4 + 4]
        life_hundreds = (packed_high >> 4) & 0x0F
        cosmo_hundreds = packed_high & 0x0F

        # The original decoder validates decimal-bearing fields, including
        # both nibbles of the packed cap byte.
        bcd_byte_to_int(life_low)
        bcd_byte_to_int(cosmo_low)
        life_cap_boundary = (cap_byte >> 4) & 0x0F
        cosmo_cap_boundary = cap_byte & 0x0F
        if (
            life_hundreds > 9
            or cosmo_hundreds > 9
            or life_cap_boundary > 9
            or cosmo_cap_boundary > 9
        ):
            raise PasswordError(f"invalid Saint record {i}")

        saints.append(
            SaintRecord(
                life_low,
                life_hundreds,
                cosmo_low,
                cosmo_hundreds,
                cap_byte,
            )
        )

    # $05AA is the lower two decimal digits, $05AB the upper two.
    low_ss = bcd_byte_to_int(payload[16])
    high_ss = bcd_byte_to_int(payload[17])
    seventh_sense = high_ss * 100 + low_ss

    mixed = payload[18]
    raw_05ac = (mixed >> 4) & 0x0F  # Mirrors ROM decoder exactly.
    progress_0100 = mixed & 0x1F

    raw_0101 = payload[19]
    raw_0588 = payload[20] & 0x0F
    raw_0587 = (payload[20] >> 4) & 0x0F
    raw_058a = payload[21] & 0x0F
    raw_0589 = (payload[21] >> 4) & 0x0F

    return DecodedPassword(
        symbols=tuple(symbols),
        payload=tuple(payload),
        saints=tuple(saints),
        seventh_sense=seventh_sense,
        raw_05ac=raw_05ac,
        progress_0100=progress_0100,
        raw_0101=raw_0101,
        raw_0587=raw_0587,
        raw_0588=raw_0588,
        raw_0589=raw_0589,
        raw_058a=raw_058a,
    )


def grid_index(row: int, column: int) -> int:
    """Convert the game's documented 1-based row/column coordinates to index."""
    if not 1 <= row <= 7 or not 1 <= column <= 10:
        raise PasswordError("grid coordinate out of range")
    return (row - 1) * 10 + (column - 1)


def known_999_fixture() -> list[int]:
    """Public 999/9999 password expressed as password-grid indices.

    Sequence: shi×6, ga×2, ze×2, ga×16, a×5.
    Published grid locations: shi=(3,2), ga=(3,6), ze=(4,9), a=(1,1).
    """
    shi = grid_index(3, 2)
    ga = grid_index(3, 6)
    ze = grid_index(4, 9)
    a = grid_index(1, 1)
    return [shi] * 6 + [ga] * 2 + [ze] * 2 + [ga] * 16 + [a] * 5


def _self_test() -> None:
    decoded = decode_symbols(known_999_fixture())
    assert len(decoded.saints) == 4
    assert all(s.life == 999 for s in decoded.saints)
    assert all(s.cosmo == 999 for s in decoded.saints)
    assert decoded.seventh_sense == 9999
    print("OK: public 999 password -> four Saints at Life/Cosmo 999, Seventh Sense 9999")
    print("caps:", [f"0x{s.cap_byte:02X}" for s in decoded.saints])
    print("payload:", " ".join(f"{b:02X}" for b in decoded.payload))


if __name__ == "__main__":
    _self_test()
